description: >
  Default executor

docker:
  - image: 'cimg/python:<<parameters.tag>>'

parameters:
  tag:
    default: "3.11.2"
    description: >
      Pick a specific circleci/base image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
